# Generated by Django 5.1.1 on 2024-10-08 17:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date_joined_previous_school', models.DateField()),
                ('exam_results', models.FileField(blank=True, null=True, upload_to='media/results/<built-in function id>', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('testimonial', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('application_fee', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('mixed', 'mixed'), ('single', 'single')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Application_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_class', models.CharField(max_length=50)),
                ('field_of_study', models.CharField(blank=True, max_length=100, null=True)),
                ('Combination', models.CharField(max_length=100)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admit.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], max_length=20)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admit.applicant')),
                ('application_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admit.application_form')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admit.school')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ammount', models.IntegerField()),
                ('status', models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid')], max_length=10)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admit.application')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='previous_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admit.school'),
        ),
    ]
