# Generated by Django 5.1.1 on 2024-10-09 18:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0002_remove_application_application_form_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='testimonial',
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/testimonials/<built-in function id>', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc', 'jpg', 'png'])])),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admit.applicant')),
            ],
        ),
    ]
