# Generated by Django 5.1.1 on 2024-10-09 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0004_testimonial_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='applicant',
        ),
    ]
